### ISSUE TITLE
Add documentation for building and running the swagger documentation 

### ISSUE THREAD

**Issue by markdturner** [e-science-central/platform#11]

**Comment by hghid** [comment]
Swagger docs are built and deployed into the App server during the normal build process. They are at:
http://localhost:8080/api/
http://localhost:8080/tokens/
http://localhost:8080/devices/

The URLS above work when everything is deployed in Docker. It needs to be added to the Readme docs, though. Probably in a build/install section

**Comment by markdturner** [comment]
Closed by commit [444874c](https://github.com/e-science-central/platform/commit/444874c13aa97f101572cbe7960a82a75130a89b)
